### PR TITLE
UX: Navigation: Rearange navigation items by scope

### PR DESCRIPTION
**Pull request by tibor-kulcar**
and add main routes to navigation bar on desktops

### CODE REVIEW

**Comment by czervenka** [comment]
Sadly, therer's a conflict. I cannot merge :(

**Comment by martinbilek** [comment]
Please postpone merge this to master until next release. This might break a lot of things and I don't want to deal with it in next release, where is still a lot of changes waiting for production deploy.

**Comment by czervenka** [comment]
> Please postpone merge this to master until next release. This might break a lot of things and I don't want to deal with it in next release, where are important changes waiting for production deploy.

The release is out now, and lives in a separate branch. Do we still want to keep this pull request on hold? @adamjezek98

**Comment by adamjezek98** [comment]
> > Please postpone merge this to master until next release. This might break a lot of things and I don't want to deal with it in next release, where are important changes waiting for production deploy.
> 
> The release is out now, and lives in a separate branch. Do we still want to keep this pull request on hold? @adamjezek98 

I think we can merge, but shouldn't PO decide that?

**Comment by czervenka** [comment]
@martinbilek can we pass this PR to next release (0.13)?

**Comment by martinbilek** [comment]
> It's more question on @tibor-kulcar and @martinbilek
> 
> @martinbilek can we pass this PR to next release (0.13)?

yes, sure! thanks guys!

**Comment by czervenka** [comment]
Rebased on top of master, waiting for checks to finish so that I can merge.

**Pull request merged**
